const Properties = [
  {
    id: 1,
    img: "./images/houseimg.jpg",
    purpose: "For Sale",
    title: "Spacious Family House",
    address: "Ikotun. Lagos State",
    price: "$20,000",
    state: 'Lagos',
    year: '2000',
    land_area: '300sqa',
    description: 'Loveley',
    // profileImg: "./images/image2.jpg",
    rooms: "1 bed",
    baths: "3 baths",
    garage: "1 garage",
    store: "1 store"
  },
  {
    id: 2,
    img: "./images/houseImg2.jpg",
    purpose: "For Rent",
    title: "Spacious Family House",
    address: "Oshodi. Lagos State",
    price: "$20,000",
    state: 'Lagos',
    year: '2000',
    land_area: '300sqa',
    description: 'Loveley',
    rooms: "1 bed",
    baths: "3 baths",
    garage: "1 garage",
    store: '1 store'
    },
  {
    id: 3,
    img: "./images/houseImg3.jpg",
    purpose: "For Sale",
    title: "Spacious Family House",
    address: "Agege. Lagos State",
    price: "$20,000",
    state: 'Lagos',
    year: '2000',
    land_area: '300sqa',
    description: 'Loveley',
    rooms: "1 bed",
    baths: "3 baths",
    garage: "1 garage",
    store: '1 store'
    },
  {
    id: 4,
    img: "./images/houseImg3.jpg",
    purpose: "For Rent",
    title: "Spacious Family House",
    address: "Agege. Lagos State",
    price: "$20,000",
    state: 'Lagos',
    year: '2000',
    land_area: '300sqa',
    description: 'Loveley',
    rooms: "1 bed",
    baths: "3 baths",
    garage: "1 garage",
    store: '1 store'
    },
  {
    id: 5,
    img: "./images/houseImg3.jpg",
    purpose: "For Sale",
    title: "Spacious Family House",
    address: "Agege. Lagos State",
    price: "$20,000",
    state: 'Lagos',
    year: '2000',
    land_area: '300sqa',
    description: 'Loveley',
    rooms: "1 bed",
    baths: "3 baths",
    garage: "1 garage",
    store: '1 store'
    },
  {
    id: 6,
    img: "./images/houseImg3.jpg",
    purpose: "For Sale",
    title: "Spacious Family House",
    address: "Agege. Lagos State",
    price: "$20,000",
    state: 'Lagos',
    year: '2000',
    land_area: '300sqa',
    description: 'Loveley',
    rooms: "1 bed",
    baths: "3 baths",
    garage: "1 garage",
    store: '1 store'
    },
  {
    id: 7,
    img: "./images/houseImg3.jpg",
    purpose: "For Rent",
    title: "Spacious Family House",
    address: "Agege. Lagos State",
    price: "$20,000",
    state: 'Lagos',
    year: '2000',
    land_area: '300sqa',
    description: 'Loveley',
    rooms: "1 bed",
    baths: "3 baths",
    garage: "1 garage",
    store: '1 store'
    },
  {
    id: 8,
    img: "./images/houseImg3.jpg",
    purpose: "For Sale",
    title: "Spacious Family House",
    address: "Agege. Lagos State",
    price: "$20,000",
    state: 'Lagos',
    year: '2000',
    land_area: '300sqa',
    description: 'Loveley',
    rooms: "1 bed",
    baths: "3 baths",
    garage: "1 garage",
    store: '1 store'
    },
];

export default Properties;
